<script setup lang="ts">
const {t,lang,local}=useLocale(); usePageSeo(computed(()=>lang.value==='ru'?'Приём SMS онлайн на временные номера':'Receive SMS online with temporary numbers'),computed(()=>lang.value==='ru'?'Каталог публичных номеров по странам и сервисам с обновляемой лентой сообщений.':'Browse public numbers by country and service with a refreshed message feed.'))
const config = useRuntimeConfig()
const [{data:countries},{data:services}]=await Promise.all([useFetch<any[]>('/api/catalog/countries'),useFetch<any[]>('/api/catalog/services')]); const selected=ref(1); const {data:numbers}=await useFetch<any[]>('/api/numbers',{query:{country:selected}})
const topCountryIds=[1,2,16,36,43,73,78,187]; const topServiceCodes=['tg','wa','go','ig','fb','dr','ds','lf']; const faq=computed(()=>lang.value==='ru'?[['Как открыть входящие SMS?','Выберите страну, откройте карточку номера и просмотрите обновляемую ленту сообщений.'],['Можно ли использовать номер для банка?','Нет. Публичные номера не подходят для банковских, платёжных и важных аккаунтов.'],['Сколько живёт номер?','Лента обновляется примерно раз в час, поэтому не рассчитывайте на постоянный доступ.']]:[['How do I view incoming SMS?','Choose a country, open a number card, and browse its refreshed message feed.'],['Can I use a number for banking?','No. Public numbers are unsuitable for banking, payments, or important accounts.'],['How long does a number last?','The feed refreshes approximately every hour, so access is not permanent.']])
useHead({script:[{type:'application/ld+json',innerHTML:computed(()=>JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebSite',name:'Signal SMS',url:config.public.siteUrl},{'@type':'FAQPage',mainEntity:faq.value.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]}))}]})
</script>
<template><div><section class="hero"><div class="hero-glow"></div><div class="shell hero-grid"><div><span class="eyebrow"><i></i>{{t.heroTag}}</span><h1>{{t.heroTitle}}</h1><p class="hero-copy">{{t.heroText}}</p><div class="hero-actions"><NuxtLink :to="local('/countries')" class="button">{{t.start}} →</NuxtLink><a :href="`/api/go/premium_card?lang=${lang}`" rel="nofollow sponsored noopener" class="button ghost">✦ {{t.private}}</a></div><div class="stats"><span><b>195</b> {{t.countries.toLowerCase()}}</span><span><b>800+</b> {{t.services.toLowerCase()}}</span><span><b>2 418</b> {{t.messages}}</span></div></div><div class="phone"><div class="phone-head"><span><i></i>{{t.online}}</span><small>signal / feed</small></div><div class="phone-number">+44 791 842 761</div><div class="sms-bubble"><img src="/images/services/tg.webp"><p><b>Telegram</b><br>Login code: <strong>381 490</strong><small>just now</small></p></div><div class="sms-bubble"><img src="/images/services/go.webp"><p><b>Google</b><br>Your verification code is <strong>764 203</strong><small>2 min</small></p></div><div class="pulse-line"><i></i><span></span></div></div></div></section>
<section class="section shell"><div class="section-head"><div><span class="kicker">01 / {{t.countries}}</span><h2>{{t.popularCountries}}</h2></div><NuxtLink :to="local('/countries')" class="text-link">{{t.all}} →</NuxtLink></div><div class="card-grid"><CountryCard v-for="c in countries?.filter(x=>topCountryIds.includes(x.id))" :key="c.id" :country="c"/></div></section>
<section class="section tint"><div class="shell"><div class="section-head"><div><span class="kicker">02 / {{t.services}}</span><h2>{{t.popularServices}}</h2></div><NuxtLink :to="local('/services')" class="text-link">{{t.all}} →</NuxtLink></div><div class="card-grid"><ServiceCard v-for="s in services?.filter(x=>topServiceCodes.includes(x.code))" :key="s.code" :service="s"/></div></div></section>
<section class="section shell"><div class="section-head"><div><span class="kicker">03 / Live</span><h2>{{t.live}}</h2></div></div><div class="number-grid"><NumberCard v-for="n in numbers?.slice(0,6)" :key="n.id" :number="n"/></div></section>
<section class="shell warning"><span>!</span><div><h3>{{t.safety}}</h3><p>{{t.safetyText}}</p></div><NuxtLink :to="local('/terms')">{{t.terms}} →</NuxtLink></section>
<section class="section shell faq"><span class="kicker">04 / FAQ</span><h2>{{lang==='ru'?'Частые вопросы':'Frequently asked questions'}}</h2><details v-for="([q,a],i) in faq" :key="q" :open="i===0"><summary>{{q}}<span>+</span></summary><p>{{a}}</p></details></section>
</div></template>
