<script setup lang="ts">
const {t,lang,local}=useLocale(); usePageSeo(
  computed(()=>lang.value==='ru'?'Приём SMS онлайн — временные виртуальные номера':'Receive SMS online — temporary virtual numbers'),
  computed(()=>lang.value==='ru'?'Каталог временных виртуальных номеров: выберите страну и сервис, изучите формат SMS-кодов и варианты приватного номера. 195 стран и 800+ сервисов.':'Temporary virtual number catalog: choose a country and service, explore SMS verification codes, and compare private number options.')
)
const config = useRuntimeConfig()
const [{data:countries},{data:services}]=await Promise.all([useFetch<any[]>('/api/catalog/countries'),useFetch<any[]>('/api/catalog/services')]); const selected=ref(1); const {data:numbers}=await useFetch<any[]>('/api/numbers',{query:{country:selected}})
const topCountryIds=[1,2,16,36,43,73,78,187]; const topServiceCodes=['tg','wa','go','ig','fb','dr','ds','lf']; const faq=computed(()=>lang.value==='ru'?[['Как выбрать временный номер для SMS?','Сначала выберите страну с подходящим телефонным кодом, затем откройте номер и проверьте нужный сервис в ленте. Для долгосрочного аккаунта используйте приватный номер.'],['Что такое виртуальный номер телефона?','Это номер, работающий без физической SIM-карты в вашем устройстве. На сайте показана демонстрационная публичная лента, которая помогает изучить формат SMS-кодов.'],['Как получить код подтверждения онлайн?','В реальном сценарии сервис-отправитель направляет одноразовый код на выбранный телефон. Публичная лента Signal SMS является симуляцией и не гарантирует доставку настоящего сообщения.'],['Можно ли использовать бесплатный номер для банка?','Нет. Публичные номера не подходят для банковских, платёжных, государственных и других важных аккаунтов.'],['Сколько живёт временный номер?','Демонстрационный набор обновляется примерно раз в час. Не рассчитывайте на постоянный доступ к одному номеру.']]:[['How do I choose a temporary SMS number?','Choose a country and calling code, then open a number and check the service shown in its feed. Use a private number for any long-term account.'],['What is a virtual phone number?','It is a number that works without a physical SIM in your device. This site shows a simulated public feed for exploring verification-code formats.'],['How do I receive a verification code online?','In a real workflow, the sender delivers a one-time code to the selected phone. The Signal SMS public feed is simulated and does not guarantee real delivery.'],['Can I use a free number for banking?','No. Public numbers are unsuitable for banking, payments, government services, or other important accounts.'],['How long does a temporary number last?','The simulated set refreshes approximately every hour. Do not rely on permanent access to one number.']])
useHead({script:[{type:'application/ld+json',innerHTML:computed(()=>JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebSite',name:'Signal SMS',url:config.public.siteUrl},{'@type':'FAQPage',mainEntity:faq.value.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]}))}]})

const heroFeed=[{code:'tg',name:'Telegram',text:'Login code:',value:'381 490'},{code:'go',name:'Google',text:'Your verification code is',value:'764 203'},{code:'wa',name:'WhatsApp',text:'Your code:',value:'512 987'},{code:'ig',name:'Instagram',text:'Use code',value:'209 654'},{code:'ds',name:'Discord',text:'Verification code:',value:'447 128'},{code:'lf',name:'TikTok',text:'Your code is',value:'930 271'}]
const heroCounter=ref(1)
const heroVisible=computed(()=>[heroCounter.value-1,heroCounter.value].map((k,i)=>({key:k,age:i===0?'1 min':'just now',...heroFeed[((k%heroFeed.length)+heroFeed.length)%heroFeed.length]})))
const messagesToday=ref(2418)
const formatCount=(n:number)=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,' ')
let heroTimer: ReturnType<typeof setInterval> | undefined
onMounted(()=>{heroTimer=setInterval(()=>{heroCounter.value++;messagesToday.value+=1+Math.floor(Math.random()*3)},3000)})
onUnmounted(()=>{if(heroTimer)clearInterval(heroTimer)})
</script>
<template><div><section class="hero"><div class="hero-glow"></div><div class="shell hero-grid"><div><span class="eyebrow"><i></i>{{t.heroTag}}</span><h1>{{lang==='ru'?'Временные номера для приёма SMS онлайн':'Temporary numbers for receiving SMS online'}}</h1><p class="hero-copy">{{lang==='ru'?'Выберите страну и сервис, чтобы изучить публичную ленту SMS-кодов. Для регистрации важного аккаунта используйте отдельный приватный номер.':t.heroText}}</p><div class="hero-actions"><NuxtLink :to="local('/countries')" class="button">{{t.start}} →</NuxtLink><a :href="`/api/go/premium_card?lang=${lang}`" rel="nofollow sponsored noopener" class="button ghost">✦ {{t.private}}</a></div><div class="stats"><span><b>195</b> {{t.countries.toLowerCase()}}</span><span><b>800+</b> {{t.services.toLowerCase()}}</span><span><b>{{formatCount(messagesToday)}}</b> {{t.messages}}</span></div></div><div class="phone"><div class="phone-head"><span><i></i>{{t.online}}</span><small>signal / feed</small></div><div class="phone-number">+44 791 842 761</div><TransitionGroup tag="div" name="sms-swipe" class="sms-feed"><div class="sms-bubble" v-for="m in heroVisible" :key="m.key"><img :src="`/images/services/${m.code}.webp`"><p><b>{{m.name}}</b><br>{{m.text}} <strong>{{m.value}}</strong><small>{{m.age}}</small></p></div></TransitionGroup><div class="pulse-line"><i></i><span></span></div></div></div></section>
<section class="section shell"><div class="section-head"><div><span class="kicker">01 / {{t.countries}}</span><h2>{{t.popularCountries}}</h2></div><NuxtLink :to="local('/countries')" class="text-link">{{t.all}} →</NuxtLink></div><div class="card-grid"><CountryCard v-for="c in countries?.filter(x=>topCountryIds.includes(x.id))" :key="c.id" :country="c"/></div></section>
<section class="section tint"><div class="shell"><div class="section-head"><div><span class="kicker">02 / {{t.services}}</span><h2>{{t.popularServices}}</h2></div><NuxtLink :to="local('/services')" class="text-link">{{t.all}} →</NuxtLink></div><div class="card-grid"><ServiceCard v-for="s in services?.filter(x=>topServiceCodes.includes(x.code))" :key="s.code" :service="s"/></div></div></section>
<section class="section shell"><div class="section-head"><div><span class="kicker">03 / Live</span><h2>{{t.live}}</h2></div></div><div class="number-grid"><NumberCard v-for="n in numbers?.slice(0,6)" :key="n.id" :number="n"/></div></section>
<section class="shell warning"><span>!</span><div><h3>{{t.safety}}</h3><p>{{t.safetyText}}</p></div><NuxtLink :to="local('/terms')">{{t.terms}} →</NuxtLink></section>
<section id="guide" class="section shell home-seo"><span class="kicker">04 / Guide</span><h2>{{lang==='ru'?'Как устроен онлайн-приём SMS':'How online SMS reception works'}}</h2><div v-if="lang==='ru'" class="home-seo-grid"><div><h3>Временный и виртуальный номер</h3><p>Виртуальный номер телефона используется без физической SIM-карты в вашем устройстве. Такой формат применяют для тестирования интерфейсов, знакомства с процессом регистрации и работы с одноразовыми кодами подтверждения. В каталоге можно выбрать телефонное направление, посмотреть код страны и перейти к связанным сервисам.</p><p>Бесплатная публичная лента доступна всем посетителям. Поэтому временный номер нельзя использовать для интернет-банка, платёжной системы, восстановления пароля или аккаунта, который должен оставаться под вашим контролем.</p></div><div><h3>Страны, сервисы и SMS-коды</h3><p>Каталог объединяет направления из 195 стран и более 800 приложений: мессенджеры, социальные сети, почтовые платформы и другие онлайн-сервисы. Внутренняя перелинковка помогает перейти от страны к номеру, а от сервиса — к доступным направлениям.</p><p>Показанные номера, статусы и входящие сообщения создаются симуляцией. Они иллюстрируют формат SMS с кодом верификации, но не обеспечивают реальный приём сообщения. Для персонального сценария используйте приватное предложение партнёра.</p></div></div><div v-else class="home-seo-grid"><div><h3>Temporary and virtual numbers</h3><p>A virtual phone number works without a physical SIM card in your device. It can help explore registration workflows and one-time verification code formats. Choose a destination to view its calling code and related services.</p><p>The public feed is visible to everyone, so never use a free number for banking, payments, password recovery, or an account you need to keep.</p></div><div><h3>Countries, services, and SMS codes</h3><p>The catalog covers 195 countries and more than 800 apps, including messengers, social networks, and email platforms. Numbers, statuses, and messages are simulated and do not provide real SMS delivery.</p></div></div></section>
<section id="faq" class="section shell faq"><span class="kicker">05 / FAQ</span><h2>{{lang==='ru'?'Частые вопросы о временных номерах':'Temporary number FAQ'}}</h2><details v-for="([q,a],i) in faq" :key="q" :open="i===0"><summary>{{q}}<span>+</span></summary><p>{{a}}</p></details></section>
</div></template>
